from __future__ import annotations
import json
import os
import re
from langchain_core.messages import AIMessage
from langgraph.types import interrupt
from faasr_agents.models import WorkflowSpec
from faasr_agents.state import AgentState
from faasr_agents.faasr.emit import emit_faasr_json, external_inputs
from faasr_agents.faasr.validate import validate_faasr_json

OUTPUT_DIR = os.path.join(os.getcwd(), "faasr_output")


def _unique_out_dir(base: str) -> str:
    """Return `base` if it's free (missing or empty), else `base-2`, `base-3`, …

    Keeps every run's artifacts intact instead of overwriting a previous run
    of the same workflow name.
    """
    candidate = base
    n = 2
    while os.path.isdir(candidate) and os.listdir(candidate):
        candidate = f"{base}-{n}"
        n += 1
    return candidate


def _save_artifacts(spec: WorkflowSpec, workflow_json: dict) -> str:
    """
    Save the workflow JSON and all function files locally.
    Returns the output directory path.
    Always runs — on both success and failure — so the user can inspect/debug.
    """
    safe_name = re.sub(r"[^a-zA-Z0-9_-]", "_", spec.name)
    out_dir = _unique_out_dir(os.path.join(OUTPUT_DIR, safe_name))
    fn_dir   = os.path.join(out_dir, "functions")
    os.makedirs(fn_dir,   exist_ok=True)

    import json as _json
    with open(os.path.join(out_dir, "workflow.json"), "w") as f:
        _json.dump(workflow_json, f, indent=2)

    for node in spec.nodes:
        if node.code:
            path = os.path.join(fn_dir, f"{node.name}.py")
            with open(path, "w") as f:
                f.write(f"# Generated by FaaSr Agent System\n")
                f.write(f"# Workflow: {spec.name}\n")
                f.write(f"# Function: {node.name}\n\n")
                f.write(node.code)

    return out_dir


def _upload_functions_to_github(spec: WorkflowSpec) -> dict:
    try:
        from github import Github, GithubException
    except ImportError:
        return {"success": False, "error": "PyGithub not installed"}

    token = os.environ.get("GH_PAT", "")
    username = os.environ.get("FAASR_GH_USERNAME", "")
    repo_name = os.environ.get("FAASR_ACTION_REPO", "")

    if not (token and username and repo_name):
        return {"success": False, "error": "GH_PAT, FAASR_GH_USERNAME, FAASR_ACTION_REPO not set"}

    try:
        g = Github(token)
        repo = g.get_repo(f"{username}/{repo_name}")
        for node in spec.nodes:
            if not node.code:
                continue
            file_path = f"functions/{node.name}.py"
            commit_msg = f"Add/update {node.name} (faasr-agents)"
            try:
                existing = repo.get_contents(file_path)
                repo.update_file(file_path, commit_msg, node.code, existing.sha)
            except GithubException as e:
                if e.status == 404:
                    repo.create_file(file_path, commit_msg, node.code)
                else:
                    raise
        return {"success": True, "error": None}
    except Exception as e:
        return {"success": False, "error": str(e)}


def _upload_workflow_json_to_github(workflow_json: dict) -> dict:
    """Commit the workflow payload JSON to the action repo at workflows/<name>.json.

    Returns the repo-relative path on success. The payload MUST live in GitHub:
    FaaSrPayload fetches it over the API and Scheduler forwards the same URL to the
    dispatched action as PAYLOAD_URL, so a local temp file can never be invoked.
    """
    try:
        from github import Github, GithubException
    except ImportError:
        return {"success": False, "error": "PyGithub not installed", "repo_path": None}

    token = os.environ.get("GH_PAT", "")
    username = os.environ.get("FAASR_GH_USERNAME", "")
    repo_name = os.environ.get("FAASR_ACTION_REPO", "")
    branch = os.environ.get("FAASR_ACTION_BRANCH", "main")

    if not (token and username and repo_name):
        return {
            "success": False,
            "error": "GH_PAT, FAASR_GH_USERNAME, FAASR_ACTION_REPO not set",
            "repo_path": None,
        }

    workflow_name = workflow_json.get("WorkflowName", "workflow")
    repo_path = f"workflows/{workflow_name}.json"
    content = json.dumps(workflow_json, indent=2)
    commit_msg = f"Add/update workflow payload {workflow_name} (faasr-agents)"

    try:
        g = Github(token)
        repo = g.get_repo(f"{username}/{repo_name}")
        try:
            existing = repo.get_contents(repo_path, ref=branch)
            repo.update_file(repo_path, commit_msg, content, existing.sha, branch=branch)
        except GithubException as e:
            if e.status == 404:
                repo.create_file(repo_path, commit_msg, content, branch=branch)
            else:
                raise
        return {"success": True, "error": None, "repo_path": repo_path}
    except Exception as e:
        return {"success": False, "error": str(e), "repo_path": None}


def _register_and_invoke(workflow_json: dict) -> dict:
    try:
        from faasr_agents.deploy.register_workflow import main as register_main
        from faasr_agents.deploy.invoke_workflow import main as invoke_main
    except ImportError as e:
        return {"success": False, "error": f"Deploy scripts not available: {e}", "faasr_payload": None}

    # Publish the payload to the action repo first so the invoke step can reference
    # it by its repo-relative path (resolved to owner/repo/branch/workflows/<name>.json).
    upload = _upload_workflow_json_to_github(workflow_json)
    if not upload["success"]:
        return {"success": False, "error": f"Payload upload failed: {upload['error']}", "faasr_payload": None}

    try:
        # register reads from the dict (no temp file needed); pass a copy so the
        # "_workflow_file" key it sets does not leak into the monitored payload.
        register_main(workflow_data=dict(workflow_json))
        # invoke_main returns a FaaSrPayload with InvocationID already generated —
        # pass it to _monitor_execution so S3 log polling targets the right run.
        faasr_payload = invoke_main(workflow_path=upload["repo_path"])
        return {"success": True, "error": None, "faasr_payload": faasr_payload}
    except Exception as e:
        return {"success": False, "error": str(e), "faasr_payload": None}


def wda_gate4_node(state: AgentState) -> dict:
    """HITL Gate 4: validate, save artifacts, and ask for deploy approval."""
    spec = state["workflow_spec"]
    iteration = state.get("iteration", 0)

    # 1. Emit + validate
    workflow_json = emit_faasr_json(spec)
    is_valid, validation_error = validate_faasr_json(workflow_json)
    if not is_valid:
        return {
            "feedback": f"Validation failed:\n{validation_error}",
            "deploy_result": {
                "success": False, "logs": "", "errors": validation_error,
                "user_message": f"FaaSr schema validation failed — the generated workflow JSON is invalid.\n\nDetails: {validation_error}",
                "failure_class": "validation",
            },
            "messages": [AIMessage(content="WDA: validation failed")],
            "iteration": iteration + 1,
        }

    # 2a. Save artifacts locally (always — enables debugging even on failure)
    out_dir = _save_artifacts(spec, workflow_json)

    # 2b. HITL Gate 4 — deploy approval
    fn_summary = "\n".join(
        f"  - {n.name} ({n.source}, {len((n.code or '').splitlines())} lines)"
        for n in spec.nodes
    )
    required_secrets = workflow_json.get("Secrets", [])
    secrets_note = ""
    if required_secrets:
        secrets_note = (
            f"\n\n⚠  Add {len(required_secrets)} secret(s) to your GitHub repo first: "
            f"{', '.join(required_secrets)} (see the list below)."
        )
    hitl_response = interrupt({
        "gate": 4,
        "message": (
            f"Ready to deploy '{spec.name}' ({len(spec.nodes)} functions).\n"
            f"{fn_summary}\n\nValidation: PASSED\n"
            f"Artifacts saved to: {out_dir}"
            f"{secrets_note}\n\n"
            "Type 'approve' to deploy, 'skip' to finish without deploying, or describe a change to revise the workflow."
        ),
        "workflow_json": workflow_json,
        "artifacts_dir": out_dir,
        "required_secrets": required_secrets,
        "external_inputs": external_inputs(spec),
    })

    resp = hitl_response.strip() if isinstance(hitl_response, str) else ""
    low = resp.lower()

    if low == "skip":
        return {
            "deploy_result": {
                "success": True, "logs": "(skipped)", "errors": "",
                "user_message": "Deployment skipped at user request. The workflow JSON is valid and ready — set GH_PAT/S3 credentials in .env and re-run to deploy.",
                "failure_class": None, "artifacts_dir": out_dir,
            },
            "messages": [AIMessage(content="WDA: deployment skipped")],
        }

    if low not in ("approve", "yes"):
        # Empty input or an explicit bail ends the run; any other text is a
        # change request → re-compose from the skeleton so topology edits
        # (e.g. rank/fan-out N) actually take effect, then re-run the gates.
        if resp == "" or low in ("decline", "cancel", "abort", "quit", "no"):
            return {
                "deploy_result": {
                    "success": False, "logs": "", "errors": "User declined deployment",
                    "user_message": "Deployment was not approved. The workflow has been composed and validated — run again and type 'approve' at Gate 4 when ready.",
                    "failure_class": "user_declined", "artifacts_dir": out_dir,
                },
                "messages": [AIMessage(content="WDA: deployment declined")],
            }
        from faasr_agents.agents.wca import classify_structural_change
        return {
            "feedback": resp,
            "revision_directives": [resp],  # accumulate so prior directives persist
            "hitl_gate": 4,
            "hitl_decision": "revise",
            "structural_change": classify_structural_change(resp, spec),
            # A function-only Gate-4 change routes to fca_resolve, skipping the skeleton;
            # stash the composed+validated spec so the FCA reuses this workflow's own
            # implementations ([cached] / adapt-from-cache). Harmless for a structural
            # change — the skeleton re-stashes prior_spec on that path.
            "prior_spec": spec,
            "deploy_result": {
                "success": False, "logs": "", "errors": "",
                "user_message": f"Revising the workflow per your request: {resp}",
                "failure_class": None, "artifacts_dir": out_dir,
            },
            "messages": [AIMessage(content="WDA: revision requested at Gate 4")],
        }

    # Approved — hand off to the deploy node. The artifacts dir is unique per
    # _save_artifacts call, so it must travel through state rather than be re-derived.
    return {
        "hitl_gate": 4,
        "hitl_decision": "approve",
        "artifacts_dir": out_dir,
        "messages": [AIMessage(content="WDA: deployment approved")],
    }


def wda_deploy_node(state: AgentState) -> dict:
    """Deploy the approved workflow (via TUI), monitor, and feed results back."""
    spec = state["workflow_spec"]
    workflow_json = emit_faasr_json(spec)
    out_dir = state["artifacts_dir"]

    # 3-5. Full deploy TUI: upload → register/invoke → live monitor
    from faasr_agents.tui.deploy_tracker import run_deploy_tui

    steps = [
        ("Upload function code to GitHub", lambda: _upload_functions_to_github(spec)),
        ("Register & invoke workflow", lambda: _register_and_invoke(workflow_json)),
    ]

    def _build_runner(faasr_payload):
        from faasr_agents.faasr.runtime.workflow_runner import WorkflowRunner
        if not os.environ.get("GITHUB_REPOSITORY"):
            gh_user = os.environ.get("FAASR_GH_USERNAME", "")
            action_repo = os.environ.get("FAASR_ACTION_REPO", "")
            if gh_user and action_repo:
                os.environ["GITHUB_REPOSITORY"] = f"{gh_user}/{action_repo}"
        if not os.environ.get("GITHUB_REF_NAME"):
            os.environ["GITHUB_REF_NAME"] = os.environ.get("FAASR_ACTION_BRANCH", "main")
        runner = WorkflowRunner(
            faasr_payload=faasr_payload,
            timeout=600,
            check_interval=10,
            stream_logs=False,
        )
        runner._start()
        return runner

    deploy = run_deploy_tui(spec, workflow_json, steps=steps, build_runner=_build_runner)

    # Infrastructure failure (upload/invoke step failed)
    if deploy["stage"] == "infra":
        error_msg = deploy.get("error", "Unknown error")
        step = deploy.get("step_label") or "deployment"
        creds_hint = ""
        if "not set" in error_msg:
            creds_hint = "\n\nTo fix: set GH_PAT, FAASR_GH_USERNAME, and FAASR_ACTION_REPO in your .env file."
        return {
            "deploy_result": {
                "success": False, "logs": "", "errors": error_msg,
                "user_message": (
                    f"Deployment failed at step '{step}'.\n\nReason: {error_msg}{creds_hint}\n\n"
                    "This is a configuration error, not a code error. The generated functions are saved."
                ),
                "failure_class": "infrastructure", "artifacts_dir": out_dir,
            },
            "messages": [AIMessage(content=f"WDA: infrastructure error — {step}: {error_msg}")],
        }

    # Execution success
    if deploy["success"]:
        return {
            "deploy_result": {
                "success": True,
                "logs": deploy.get("logs", ""),
                "errors": "",
                "user_message": (
                    f"Workflow executed successfully on GitHub Actions.\n"
                    f"Invocation: {deploy.get('invocation_id', 'N/A')}"
                ),
                "failure_class": None,
                "artifacts_dir": out_dir,
            },
            "messages": [AIMessage(content="WDA: workflow completed successfully")],
        }

    # Execution failure — hand the run to the Gate-5 post-run review. The WDA
    # summary there inspects the real logs/artifacts and may end with a
    # "Recommended revision:" the user can submit; nothing is revised automatically.
    return {
        "deploy_result": {
            "success": False,
            "logs": deploy.get("logs", ""),
            "errors": deploy.get("errors", ""),
            "failed_functions": deploy.get("failed_functions", []),
            "user_message": (
                f"Execution failed.\n"
                f"Failed functions: {deploy.get('failed_functions', [])}\n\n"
                "Opening the post-run review — inspect the logs and outputs, then "
                "accept or request a revision."
            ),
            "failure_class": "execution", "artifacts_dir": out_dir,
        },
        "messages": [AIMessage(content="WDA: execution failed — routing to post-run review")],
    }
