#!/usr/bin/env python3
"""
Interactive setup script — fills in .env from .env.template.
Run once: python3 setup_env.py
"""
import os
import re
import sys
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent
TEMPLATE = ROOT / ".env.template"
ENV_FILE = ROOT / ".env"

BOLD  = lambda t: f"\033[1m{t}\033[0m"
DIM   = lambda t: f"\033[2m{t}\033[0m"
CYAN  = lambda t: f"\033[96m{t}\033[0m"
GREEN = lambda t: f"\033[92m{t}\033[0m"
YELLOW= lambda t: f"\033[93m{t}\033[0m"
RED   = lambda t: f"\033[91m{t}\033[0m"

HINTS = {
    "BEDROCK_API_KEY":       "from the Bedrock console — looks like BedrockAPIKey-xxxx (Bedrock is the default provider)",
    "AWS_REGION":            "Bedrock region, e.g. us-east-1",
    "ANTHROPIC_API_KEY":     "sk-ant-... from console.anthropic.com — ONLY used when running with --anthropic-api",
    "OPENAI_API_KEY":        "sk-proj-... from platform.openai.com — ONLY used when running with --openai-api",
    "FAASR_OPENAI_MODEL":    "OpenAI model for --openai-api, e.g. gpt-5",
    "GH_PAT":                "github.com → Settings → Developer settings → Personal access tokens (repo + workflow scopes)",
    "FAASR_GH_USERNAME":     "your GitHub username",
    "FAASR_ACTION_REPO":     "repo where FaaSr function code will be pushed (must exist)",
    "FAASR_S3_ENDPOINT":     "leave as-is for AWS S3, or set to MinIO/R2/etc endpoint",
    "FAASR_S3_BUCKET":       "S3 bucket name for workflow data",
    "FAASR_S3_REGION":       "region of the S3 bucket",
    "S3_AccessKey":          "access key with S3 read/write on the bucket",
    "S3_SecretKey":          "corresponding secret key",
}

OPTIONAL = {"ANTHROPIC_API_KEY", "OPENAI_API_KEY", "FAASR_OPENAI_MODEL"}
DEFAULTS = {
    "AWS_REGION":        "us-east-1",
    "FAASR_OPENAI_MODEL": "gpt-5",
    "FAASR_S3_ENDPOINT": "https://s3.amazonaws.com",
    "FAASR_S3_REGION":   "us-east-1",
}


def _detect_aws_profile() -> dict[str, str]:
    """Try to pull credentials from the current AWS profile via boto3."""
    try:
        import boto3
        session = boto3.Session()
        creds = session.get_credentials()
        if creds:
            creds = creds.resolve()
            return {
                "AWS_ACCESS_KEY_ID":     creds.access_key or "",
                "AWS_SECRET_ACCESS_KEY": creds.secret_key or "",
                "AWS_SESSION_TOKEN":     creds.token or "",
                "AWS_REGION":            session.region_name or "us-east-1",
            }
    except Exception:
        pass
    return {}


def _read_existing() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    existing: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()
    return existing


def _parse_template() -> list[tuple[str, str]]:
    """Return list of (key, comment) from the template, preserving section order."""
    items: list[tuple[str, str]] = []
    for line in TEMPLATE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key = line.split("=")[0].strip()
        items.append(key)
    return items


def main() -> None:
    print()
    print(BOLD(CYAN("  FaaSr Agent System — environment setup")))
    print(DIM("  Fills in .env from .env.template. Press Enter to keep existing/default values."))
    print()

    if not TEMPLATE.exists():
        print(RED(f"  Error: {TEMPLATE} not found."))
        sys.exit(1)

    existing = _read_existing()
    if existing:
        print(f"  {YELLOW('!')} Found existing .env — pre-filling from it.")
        print()

    keys = _parse_template()
    values: dict[str, str] = {}

    current_section = None
    sections = {
        "BEDROCK_API_KEY":    "LLM credentials",
        "GH_PAT":             "GitHub",
        "FAASR_S3_ENDPOINT":  "S3 storage",
    }

    for key in keys:
        if key in sections:
            print(f"  {BOLD('──')} {sections[key]}")
            print()

        hint    = HINTS.get(key, "")
        default = existing.get(key) or DEFAULTS.get(key, "")
        optional = key in OPTIONAL

        label = DIM("[optional] ") if optional else ""
        default_display = DIM(f" [{default}]") if default else ""
        if hint:
            print(f"  {DIM(hint)}")

        prompt = f"  {label}{BOLD(key)}{default_display}: "
        try:
            val = input(prompt).strip()
        except (EOFError, KeyboardInterrupt):
            print()
            print(DIM("  Aborted."))
            sys.exit(0)

        if not val:
            val = default
        values[key] = val
        print()

    # Write .env
    lines = [
        "# Auto-generated by setup_env.py — do not commit this file",
        "",
    ]
    section_headers = {
        "LLM credentials": "# ── LLM credentials ──────────────────────────────────",
        "GitHub":          "# ── GitHub ───────────────────────────────────────────",
        "S3 storage":      "# ── S3-compatible storage ────────────────────────────",
    }
    emitted_sections: set[str] = set()
    for key in keys:
        sec = sections.get(key)
        if sec and sec not in emitted_sections:
            lines.append(section_headers[sec])
            emitted_sections.add(sec)
        lines.append(f"{key}={values.get(key, '')}")

    ENV_FILE.write_text("\n".join(lines) + "\n")

    print(f"  {GREEN('✔')} Written to {ENV_FILE}")
    print()

    # Quick validation
    missing = [k for k in keys if k not in OPTIONAL and not values.get(k)]
    if missing:
        print(f"  {YELLOW('⚠')}  The following required values are empty:")
        for k in missing:
            print(f"     {RED(k)}")
        print(f"  {DIM('Edit .env and fill them in before running faasr-agents.')}")
    else:
        print(f"  {GREEN('✔')} All required values set. Run:  {BOLD('faasr-agents')}")
    print()


if __name__ == "__main__":
    main()
